/*
 * This file was automatically generated by oml2-scaffold V2.10.0
 * for click_mon version 0.9.1.
 * 
 */

#define PACKAGE			"click_mon"
#define VERSION			"0.9.1"

/* Provide compatibility with autoconf-generated config.h */
#define PACKAGE_NAME		PACKAGE
#define PACKAGE_TAR_NAME	PACKAGE
#define PACKAGE_VERSION		VERSION

