/*
 * This file was automatically generated by oml2-scaffold V2.10.0
 * for click_mon version 0.9.1.
 * Please edit to suit your needs; the run() function should contain application code.
 */

#include <unistd.h> /* Needed for sleep(3) in run() */
#include <popt.h>
#include <oml2/omlc.h>

#define USE_OPTS /* Include command line parsing code*/
#include "click_mon_popt.h"

#define OML_FROM_MAIN /* Define storage for some global variables; #define this in only one file */
#include "click_mon_oml.h"

#include "config.h"

/* Do application-specific work here */
void
run(opts_t* opts, oml_mps_t* oml_mps)
{
  long val = 1;

  do {
    /* The oml_inject_MPNAME() helpers are defined in click_mon_oml.h*/
    oml_inject_packet_stats(oml_mps->packet_stats, ((uint32_t)val), "foo", "foo", ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), 1.0/val, 1.0/val);
    oml_inject_link_stats(oml_mps->link_stats, ((uint32_t)val), "foo", "foo", "foo", 1.0/val, ((uint32_t)val), ((uint32_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), 1.0/val, 1.0/val);
    oml_inject_routing_stats(oml_mps->routing_stats, ((uint32_t)val), "foo", ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val), ((uint64_t)val));

    val += 2;
    sleep(1);
  } while (1);
}

int
main(int argc, const char *argv[])
{
  int c, ret;

  if((ret = omlc_init("click_mon", &argc, argv, NULL)) < 0) {
    logerror("Could not initialise OML\n");
    return -1;
  }

  /* Parse command line arguments */
  poptContext optCon = poptGetContext(NULL, argc, argv, options, 0); /* options is defined in click_mon_popt.h */
  while ((c = poptGetNextOpt(optCon)) > 0) {}

  /* Initialise measurement points, only if OML is not disabled */
  oml_register_mps(); /* Defined in click_mon_oml.h */
  if(ret == 0 && omlc_start()) {
    logerror("Could not start OML\n");
    return -1;
  }

  run(g_opts, g_oml_mps_click_mon); /* Do some work and injections, see above */

  omlc_close();

  return 0;
}

/*
 Local Variables:
 mode: C
 tab-width: 2
 indent-tabs-mode: nil
 End:
 vim: sw=2:sts=2:expandtab
*/
